joint_trajectory_controller:
  ros__parameters:
    joints:
    - joint_0
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6

    command_interfaces:
      - position
    state_interfaces:
      - position
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_nonzero_velocity_at_trajectory_end: true

kuka_kr60_arm_controller:
  ros__parameters:
    joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6

    command_interfaces:
      - position
    state_interfaces:
      - position
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_nonzero_velocity_at_trajectory_end: True

kuka_track_controller:
  ros__parameters:
    joints:
    - joint_0

    command_interfaces:
      - position
    state_interfaces:
      - position
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_nonzero_velocity_at_trajectory_end: True
