controller_manager:
  ros__parameters:
    update_rate: 250  # Hz

    kuka_kr60_arm_controller: #joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    kuka_track_controller: #joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    configure_components_on_start: [""]
